#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

redirect_cmd exec s6-setuidgid abc \
	/app/Jackett/jackett \
	-x \
	-d /config \
	--NoUpdates
