#!/usr/bin/with-contenv bash

# may prevent some headaches
if [ -d /config/Jackett ]; then
	mv /config/Jackett/* /config
	rm -rf /config/Jackett
fi

chown -R abc:abc \
	/config

chown -R abc:abc \
	/app/Jackett
